import player1 from './resource/images/player/이승호.jpeg'
import player0 from './resource/images/player/김영찬.jpeg'
import player2 from './resource/images/player/강민석.jpeg'
import player8 from './resource/images/player/김선회.jpeg'
import player13 from './resource/images/player/김성현.jpeg'
import player4 from './resource/images/player/김재현.jpeg'
import player12 from './resource/images/player/김창오.jpeg'
import player6 from './resource/images/player/설민찬.jpeg'
import player7 from './resource/images/player/유형석.jpeg'
import player11 from './resource/images/player/윤인권.jpeg'

export const playerData = [
        {
            id: 0,
            name: '김영찬',
            img: `${player0}`,
            height: '176cm',
            age: '25',
            country: '대한민국',
            character: '캣맘',
            mostUsedFoot: '오른발',
            skill: 4,
            ability: [8, 9, 6, 8, 10, 7],
            total: 48,
        },
        {
            id: 1,
            name: '이승호',
            img: `${player1}`,
            height: '179cm',
            age: '25',
            country: '대한민국',
            character: '기흉, Agent',
            mostUsedFoot: '오른발',
            skill: 5,
            ability: [6, 6, 3, 6, 6, 4],
            total: 31,
        },
        {
            id: 2,
            name: '강민석',
            img: `${player2}`,
            height: '173cm',
            age: '25',
            country: '대한민국',
            character: '살인',
            mostUsedFoot: '오른발',
            skill: 3,
            ability: [6, 5, 6, 6, 7, 6],
            total: 36,
        },
        {
            id: 3,
            name: '임동주',
            img: `${player1}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '해병대, 헬창',
            mostUsedFoot: '오른발',
            skill: 3,
            ability: [7, 5, 9, 6, 6, 7],
            total: 40,
        },
        {
            id: 4,
            name: '김재현',
            img: `${player4}`,
            height: '180cm',
            age: '25',
            country: '대한민국',
            character: '패배주의보',
            mostUsedFoot: '오른발',
            skill: 3,
            ability: [7, 6, 8, 9, 8, 8],
            total: 46,
        },
        {
            id: 5,
            name: '유인재',
            img: `${player2}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '몸빵, 헬창',
            mostUsedFoot: '왼발',
            skill: 3,
            ability: [8, 6, 10, 6, 6, 7],
            total: 43,
        },
        {
            id: 6,
            name: '설민찬',
            img: `${player6}`,
            height: '176cm',
            age: '25',
            country: '대한민국',
            character: '축린이',
            mostUsedFoot: '왼발',
            skill: 1,
            ability: [3, 4, 7, 6, 10, 1],
            total: 31,
        },
        {
            id: 7,
            name: '유형석',
            img: `${player7}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '형명보, 빨딱',
            mostUsedFoot: '오른발',
            skill: 4,
            ability: [8, 7, 7, 7, 8, 10],
            total: 47,
        },
        {
            id: 8,
            name: '김선회',
            img: `${player8}`,
            height: '177cm',
            age: '25',
            country: '대한민국',
            character: 'No 재현 운동',
            mostUsedFoot: '오른발',
            skill: 2,
            ability: [1, 6, 8, 6, 6, 7],
            total: 34,
        },
        {
            id: 9,
            name: '송찬익',
            img: `${player1}`,
            height: '170cm',
            age: '25',
            country: '대한민국',
            character: '섬주민, 어부',
            mostUsedFoot: '오른발',
            skill: 5,
            ability: [7, 10, 5, 4, 7, 7],
            total: 40,
        },
        {
            id: 10,
            name: '최태경',
            img: `${player1}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '송찬익 깐부',
            mostUsedFoot: '오른발',
            skill: 3,
            ability: [9, 9, 7, 6, 7, 8],
            total: 46,
        },
        {
            id: 11,
            name: '윤인권',
            img: `${player11}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '강원도 시민',
            mostUsedFoot: '오른발',
            skill: 2,
            ability: [5, 5, 7, 6, 7, 5],
            total: 35,
        },
        {
            id: 12,
            name: '김창오',
            img: `${player12}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '첼시 유니폼',
            mostUsedFoot: '오른발',
            skill: 3,
            ability: [7, 7, 7, 8, 8, 7],
            total: 44,
        },
        {
            id: 13,
            name: '김성현',
            img: `${player13}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '오타쿠, 기린',
            mostUsedFoot: '오른발',
            skill: 5,
            ability: [7, 6, 8, 7, 7, 6],
            total: 44,
        }, {
            id: 14,
            name: '신승환',
            img: `${player13}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '난 이제 시작이야',
            mostUsedFoot: '오른발',
            skill: 4,
            ability: [8, 7, 6, 8, 7, 9],
        total: 45,
        },
        {
            id: 15,
            name: '임준수',
            img: `${player13}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '송현고 베스트11',
            mostUsedFoot: '오른발',
            skill: 4,
            ability: [10, 10, 7, 9, 10, 10],
            total: 56,
        },
        {
            id: 16,
            name: '김민형',
            img: `${player13}`,
            height: '174cm',
            age: '25',
            country: '대한민국',
            character: '신곡중 골키퍼',
            mostUsedFoot: '완발',
            skill: 3,
            ability: [8, 8, 7, 8, 8, 8],
            total: 47,
        },
    ]
;
